// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd81GwJIK3S0IBeUWBAGjvf6u-Hdqucjw',
    appId: '1:72922634717:web:1eba28d2b6fe2a5bae3e34',
    messagingSenderId: '72922634717',
    projectId: 'todo-app-b34d3',
    authDomain: 'todo-app-b34d3.firebaseapp.com',
    storageBucket: 'todo-app-b34d3.firebasestorage.app',
    measurementId: 'G-8SXV14VR48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlNa4IWW8V35MXtctyjUV962skaOqQHqc',
    appId: '1:72922634717:android:bc6c05af121a50a6ae3e34',
    messagingSenderId: '72922634717',
    projectId: 'todo-app-b34d3',
    storageBucket: 'todo-app-b34d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAioAU22pBf2_upfmcI9tuJ61VxMIld2VI',
    appId: '1:72922634717:ios:caaff7d74cf4106bae3e34',
    messagingSenderId: '72922634717',
    projectId: 'todo-app-b34d3',
    storageBucket: 'todo-app-b34d3.firebasestorage.app',
    iosBundleId: 'com.example.figmaLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAioAU22pBf2_upfmcI9tuJ61VxMIld2VI',
    appId: '1:72922634717:ios:caaff7d74cf4106bae3e34',
    messagingSenderId: '72922634717',
    projectId: 'todo-app-b34d3',
    storageBucket: 'todo-app-b34d3.firebasestorage.app',
    iosBundleId: 'com.example.figmaLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd81GwJIK3S0IBeUWBAGjvf6u-Hdqucjw',
    appId: '1:72922634717:web:953d827f98d9a216ae3e34',
    messagingSenderId: '72922634717',
    projectId: 'todo-app-b34d3',
    authDomain: 'todo-app-b34d3.firebaseapp.com',
    storageBucket: 'todo-app-b34d3.firebasestorage.app',
    measurementId: 'G-FF4KPLFE8H',
  );
}
